name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ocaml:
    name: OCaml (dune runtest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml (opam)
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1
          dune-cache: true

      - name: Cache opam
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-5.2.1-${{ hashFiles('**/*.opam') }}
          restore-keys: |
            ${{ runner.os }}-opam-5.2.1-

      - name: Install deps (dune + project + alcotest)
        run: |
          opam update
          opam install -y dune alcotest
          opam install -y . --deps-only

      - name: Build & test (via opam exec)
        run: |
          opam exec -- dune build
          opam exec -- dune runtest

  go:
    name: Go tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download deps
        run: go mod download

      - name: Run tests
        run: go test -v ./...
